#!/usr/bin/sh
python train_mingpt.py --dataset_type fashion \
       --work_dir work/mingpt \
       --log_iter 300 \
       --save_iter 1000 \
       --eval_iter 300 \
       --n_embed 128 \
       --n_head 8 \
       --n_layer 4 \
       --pdropout 0.01 \
       --batch_size 32 \
       --learning_rate 6e-4 \
       --n_epoch 32 \
       --n_warmup 1000 \
       --downscale 2 \
       --row 5 \
       --num_beams 2 \
       --temperature 2 \
       --seed 0 \
       --data_dir=data \
       --unconditional